#ifndef MESSAGECODES_E_H
#define MESSAGECODES_E_H

enum MessageCodes_E
{
	NO_MESSAGE = 0,
	INVALID_COM_ERR = 1,
	FILENAME_NOT_SPEC_ERR = 2,
	INVALID_AMOUNT_ERR = 3,
	COULD_NOT_CREATE_ERR = 4,
	WALLET_EXISTS_ERR = 5,
	INVALID_PARAM_ERR = 6,
	INCOME_SPEND_HIGHER_ERR = 7,
	COULD_NOT_OPEN_FILE_ERR = 8,
	COULD_NOT_OPEN_CONFIG_ERR = 9,
	NO_DEFAULT_WALLET_ERR = 10,
	NO_TRANSACTION_REG_ERR = 11,
	NO_VALID_CONFIG_VALUE_ERR = 12,
	WALLET_CRETED_MSG = 13,
	SPEND_INCOME_REGISTERED_MSG = 14,
	BALANCE_IS_MSG = 15,
	TAG_CONFIGURED_MSG = 16,
	HELP_MSG = 17,
	COULD_NOT_OPEN_FILE_BAL_ERR =18
};

#endif