#ifndef MESSAGECODES_E_H
#define MESSAGECODES_E_H

enum MessageCodes_E
{
	NO_MESSAGE,
	INVALID_COM_ERR,
	FILENAME_NOT_SPEC_ERR,
	INVALID_AMOUNT_ERR,
	COULD_NOT_CREATE_ERR,
	WALLET_EXISTS_ERR,
	INVALID_PARAM_ERR,
	INCOME_SPEND_HIGHER_ERR,
	COULD_NOT_OPEN_FILE_ERR,
	COULD_NOT_OPEN_CONFIG_ERR,
	NO_DEFAULT_WALLET_ERR,
	NO_TRANSACTION_REG_ERR,
	NO_VALID_CONFIG_VALUE_ERR,
	WALLET_CRETED_MSG,
	SPEND_INCOME_REGISTERED_MSG,
	BALANCE_IS_MSG,
	TAG_CONFIGURED_MSG,
	HELP_MSG
};

#endif